//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------------ Functions -------------------------

// Address range: 0x40161f - 0x401620
int main(int argc, char ** argv) {
    // 0x40161f
    int64_t result; // 0x40161f
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (9.4.0)
// Detected functions: 1
